@baseUrl = http://localhost:9292
@session = mysession=MTc0OTg1Nzc5MHxEWDhFQVFMX2dBQUJFQUVRQUFBb180QUFBUVp6ZEhKcGJtY01DQUFHYzNSaGRIVnpCbk4wY21sdVp3d0tBQWhoWTNScGRtRjBaUT09fMsOMrySaZXb7iVqWPzRGdBZzMNWzsX53YvrKgdxuykg

### Listar issue-states
GET {{baseUrl}}/apis/v1/issue-states
Content-Type: application/json
Cookie: {{session}}

### Crear tag
POST {{baseUrl}}/apis/v1/issue-states
Content-Type: application/json
Cookie: {{session}}

{
  "name": "volley"
}

### Actualizar tag
PUT {{baseUrl}}/apis/v1/issue-states/6858a661c99c8d1b9aab8201
Content-Type: application/json
Cookie: {{session}}

{
  "name": "futbol 2222"
}

### Actualizar delete
DELETE {{baseUrl}}/apis/v1/issue-states/6858a661c99c8d1b9aab8201
Content-Type: application/json
Cookie: {{session}}
