@baseUrl = http://localhost:9292
@session = mysession=MTc0OTg1Nzc5MHxEWDhFQVFMX2dBQUJFQUVRQUFBb180QUFBUVp6ZEhKcGJtY01DQUFHYzNSaGRIVnpCbk4wY21sdVp3d0tBQWhoWTNScGRtRjBaUT09fMsOMrySaZXb7iVqWPzRGdBZzMNWzsX53YvrKgdxuykg

### Listar prioritys
GET {{baseUrl}}/apis/v1/priorities
Content-Type: application/json
Cookie: {{session}}

### Crear priority
POST {{baseUrl}}/apis/v1/priorities
Content-Type: application/json
Cookie: {{session}}

{
  "name": "volley"
}

### Actualizar priority
PUT {{baseUrl}}/apis/v1/priorities/6858a7aad64d60157a1afffe
Content-Type: application/json
Cookie: {{session}}

{
  "name": "futbol 2222"
}

### Actualizar delete
DELETE {{baseUrl}}/apis/v1/priorities/6858a793d64d60157a1afffd
Content-Type: application/json
Cookie: {{session}}
