@baseUrl = http://localhost:9292
@session = mysession=MTc0OTg1Nzc5MHxEWDhFQVFMX2dBQUJFQUVRQUFBb180QUFBUVp6ZEhKcGJtY01DQUFHYzNSaGRIVnpCbk4wY21sdVp3d0tBQWhoWTNScGRtRjBaUT09fMsOMrySaZXb7iVqWPzRGdBZzMNWzsX53YvrKgdxuykg

@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ5b3VyLWFwcC5jb20iLCJhdWQiOiJ5b3VyLWNsaWVudC1pZCIsInN1YiI6InVzZXJAZXhhbXBsZS5jb20iLCJleHAiOjE3NTEwOTA0NDAsImlhdCI6MTc1MTA4Njg0MCwidXNlcl9pZCI6MTIzLCJyb2xlIjoiYWRtaW4ifQ.g5YDIg7pdsqPnIhof5qdLm3lS9Ik2hkUJQ853xQ-CkM

### Listar tags
GET {{baseUrl}}/api/v1/tags
Content-Type: application/json
Cookie: {{session}}
Authorization: Bearer {{token}}

### Crear tag
POST {{baseUrl}}/api/v1/tags
Content-Type: application/json
Cookie: {{session}}

{
  "name": "volley"
}

### Actualizar tag
PUT {{baseUrl}}/api/v1/tags/6858a32064aaf0378e72f795
Content-Type: application/json
Cookie: {{session}}

{
  "name": "futbol 2222"
}

### Actualizar delete
DELETE {{baseUrl}}/api/v1/tags/6858a09043d00b901ea6b7ea
Content-Type: application/json
Cookie: {{session}}
