@startuml

class Employee {
  - _id: ObjectId
  - names: String
  - lastNames: String
  - created: DateTime
  - updated: DateTime
  - userId: int
}

class Priority {
  - _id: ObjectId
  - name: String
  - created: DateTime
  - updated: DateTime
}

class Asset {
  - _id: ObjectId
  - name: String
  - description: String
  - created: DateTime
  - updated: DateTime
}

class Tag{
  - _id: ObjectId
  - name: String
  - created: DateTime
  - updated: DateTime
}

class IssueState {
  - _id: ObjectId
  - name: String
  - created: DateTime
  - updated: DateTime
}

class Issue {
  - _id: ObjectId
  - name: String
  - description: String
  - issueStateId: ObjectId
  - priorityId: ObjectId
  - assetsIds: Array[ObjectIds]
  - tagsIds: Array[ObjectIds]
  - visorsIds: Array[ObjectIds]
  - editorsIds: Array[ObjectIds]
  - histories: Array[History]
  - documents: Array[Document]
  - reportered: ObjectId
  - created: DateTime
  - updated: DateTime
}

class History {
  - _id: ObjectId
  - description: String
  - employeeId: ObjectId
  - documents: Array[Document]
  - created: DateTime
  - updated: DateTim
}

class Document {
  - _id: ObjectId
  - name: String
  - description: String
  - mime: String
  - url: String
  - created: DateTime
}

Issue "n" *-- "1" Employee : crea
Issue "n" *-- "n" Employee : mira
Issue "n" *-- "n" Employee : edita
Issue "n" *-- "1" IssueState : tiene
Issue "n" *-- "1" Priority : tiene
Issue "n" o-- "n" Asset : tiene
Issue "n" o-- "n" Tag : tiene
Issue "1" o-- "n" History : tiene
Issue "1" o-- "n" Document : tiene
History "1" o-- "n" Document : tiene

@enduml
